name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: LaTeX compilation
      uses: dante-ev/latex-action@v0.2.0
      with:
        root_file: guide.tex
    - name: Upload PDF
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/utwente-fmt/tool-server/releases/latest/assets?name=guide.pdf
        asset_path: guide.pdf
        asset_name: guide.pdf
        asset_content_type: application/pdf
